# Generated by Django 6.0 on 2026-03-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=255)),
                ('collegeName', models.CharField(max_length=255)),
                ('collegeCode', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_type', models.CharField(default='PDF', max_length=50)),
                ('size', models.CharField(default='0 MB', max_length=50)),
                ('fileUrl', models.URLField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=255)),
                ('collegeName', models.CharField(max_length=255)),
                ('collegeCode', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(default='Upcoming', max_length=50)),
                ('questions_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
