# Generated by Django 6.0.3 on 2026-03-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
