# Generated by Django 6.0 on 2026-03-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_test_status_question_testsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=255)),
                ('studentName', models.CharField(max_length=255)),
                ('teacherId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(default='0 MB', max_length=50)),
                ('file', models.FileField(upload_to='assignments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
